const players=[
    {
        name:'Dave',
        rank:1,
        bye:3,
        team:'Eagles',
    },
    {
        name:'Joe',
        rank:2,
        bye:7,
        team:'Bucs',
    },
    {
        name:'Bill',
        rank:3,
        bye:5,
        team:'Bills',
    },
    {
        name:'Tony',
        rank:4,
        bye:7,
        team:'Cowboys',
    },
    {
        name:'Bobby',
        rank:6,
        bye:8,
        team:'Rams',
    },
    {
        name:'Mike',
        rank:5,
        bye:3,
        team:'49ers',
    },
    {
        name:'Peter',
        rank:7,
        bye:8,
        team:'Vikings',
    },
    {
        name:'Jamal',
        rank:8,
        bye:5,
        team:'Browns',
    },
    {
        name:'Drew',
        rank:9,
        bye:7,
        team:'Saints',
    },
    {
        name:'Terry',
        rank:10,
        bye:8,
        team:'Jags',
    },
    {
        name:'Phil',
        rank:11,
        bye:3,
        team:'WFT',
    },
    {
        name:'Justin',
        rank:12,
        bye:7,
        team:'Jets',
    }
]
export default players
